version: "3.8"

services:
  # api:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #     - PORT=3000
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   networks:
  #     - mimi_network
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379" # Redis port
      - "8001:8001" # RedisInsight port
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS="--requirepass mypassword" # Optional: set password
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - mimi_network
    deploy:
      resources:
        limits:
          memory: 3g # Recommended for vector search operations

networks:
  mimi_network:
    driver: bridge

volumes:
  redis_data:
